name: Run system tests

on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  system-tests:
    name: RETI unit and system tests
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v6

      - name: Install build dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libncurses-dev

      - name: Build emulator
        run: make ci-build LINUX=1 RELEASE=1

      - name: Run unit tests
        run: make unit-test LINUX=1 RELEASE=1

      - name: Run system tests
        run: ./run_sys_tests.sh 120
